# Generated by Django 4.1.5 on 2023-01-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeltaHacks9', '0003_remove_smallbusiness_url_smallbusiness_photos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smallbusiness',
            name='name',
        ),
        migrations.RemoveField(
            model_name='smallbusiness',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='smallbusiness',
            name='rating',
        ),
        migrations.AddField(
            model_name='smallbusiness',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
