# Generated by Django 4.1.5 on 2023-01-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeltaHacks9', '0004_remove_smallbusiness_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smallbusiness',
            old_name='data',
            new_name='photos',
        ),
        migrations.AddField(
            model_name='smallbusiness',
            name='name',
            field=models.CharField(default=dict, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smallbusiness',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
